
services:
  - type: web
    name: voc-backend
    env: python
    plan: free
    region: singapore
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    autoDeploy: true
